<template>
    <svg xmlns="http://www.w3.org/2000/svg" width="67" height="13" viewBox="0 0 67 13" fill="none">
        <rect x="23" y="4" width="44" height="5" fill="#D9D9D9"/>
        <ellipse cx="12.5" cy="6.5" rx="12.5" ry="6.5" fill="#D9D9D9"/>
        <rect x="5" y="4" width="2" height="2" fill="white"/>
        <rect x="2" y="3" width="2" height="2" fill="white"/>
        <rect x="7" y="5" width="2" height="2" fill="white"/>
        <rect x="9" y="5" width="2" height="2" fill="white"/>
        <rect x="6" y="4" width="2" height="2" fill="white"/>
        <rect x="11" y="6" width="2" height="2" fill="white"/>
        <rect x="11" y="3" width="2" height="2" fill="white"/>
        <rect x="8" y="2" width="2" height="2" fill="white"/>
        <rect x="13" y="4" width="2" height="2" fill="white"/>
        <rect x="7" y="5" width="2" height="2" fill="white"/>
        <rect x="4" y="4" width="2" height="2" fill="white"/>
        <rect x="9" y="6" width="2" height="2" fill="white"/>
        <rect x="11" y="6" width="2" height="2" fill="white"/>
        <rect x="8" y="5" width="2" height="2" fill="white"/>
        <rect x="13" y="7" width="2" height="2" fill="white"/>
        <rect x="13" y="4" width="2" height="2" fill="white"/>
        <rect x="10" y="3" width="2" height="2" fill="white"/>
        <rect x="15" y="5" width="2" height="2" fill="white"/>
        <rect x="6" y="7" width="2" height="2" fill="white"/>
        <rect x="3" y="6" width="2" height="2" fill="white"/>
        <rect x="8" y="8" width="2" height="2" fill="white"/>
        <rect x="10" y="8" width="2" height="2" fill="white"/>
        <rect x="7" y="7" width="2" height="2" fill="white"/>
        <rect x="12" y="9" width="2" height="2" fill="white"/>
        <rect x="12" y="6" width="2" height="2" fill="white"/>
        <rect x="9" y="5" width="2" height="2" fill="white"/>
        <rect x="14" y="7" width="2" height="2" fill="white"/>
        <rect x="8" y="8" width="2" height="2" fill="white"/>
        <rect x="5" y="7" width="2" height="2" fill="white"/>
        <rect x="10" y="9" width="2" height="2" fill="white"/>
        <rect x="12" y="9" width="2" height="2" fill="white"/>
        <rect x="9" y="8" width="2" height="2" fill="white"/>
        <rect x="14" y="10" width="2" height="2" fill="white"/>
        <rect x="14" y="7" width="2" height="2" fill="white"/>
        <rect x="11" y="6" width="2" height="2" fill="white"/>
        <rect x="16" y="8" width="2" height="2" fill="white"/>
        <rect x="9" y="6" width="2" height="2" fill="white"/>
        <rect x="6" y="5" width="2" height="2" fill="white"/>
        <rect x="11" y="7" width="2" height="2" fill="white"/>
        <rect x="13" y="7" width="2" height="2" fill="white"/>
        <rect x="10" y="6" width="2" height="2" fill="white"/>
        <rect x="15" y="8" width="2" height="2" fill="white"/>
        <rect x="15" y="5" width="2" height="2" fill="white"/>
        <rect x="12" y="4" width="2" height="2" fill="white"/>
        <rect x="17" y="6" width="2" height="2" fill="white"/>
        <rect x="9" y="4" width="2" height="2" fill="white"/>
        <rect x="6" y="3" width="2" height="2" fill="white"/>
        <rect x="11" y="5" width="2" height="2" fill="white"/>
        <rect x="13" y="5" width="2" height="2" fill="white"/>
        <rect x="10" y="4" width="2" height="2" fill="white"/>
        <rect x="15" y="6" width="2" height="2" fill="white"/>
        <rect x="15" y="3" width="2" height="2" fill="white"/>
        <rect x="12" y="2" width="2" height="2" fill="white"/>
        <rect x="17" y="4" width="2" height="2" fill="white"/>
        <rect x="8" y="6" width="2" height="2" fill="white"/>
        <rect x="5" y="5" width="2" height="2" fill="white"/>
        <rect x="10" y="7" width="2" height="2" fill="white"/>
        <rect x="12" y="7" width="2" height="2" fill="white"/>
        <rect x="9" y="6" width="2" height="2" fill="white"/>
        <rect x="14" y="8" width="2" height="2" fill="white"/>
        <rect x="14" y="5" width="2" height="2" fill="white"/>
        <rect x="11" y="4" width="2" height="2" fill="white"/>
        <rect x="16" y="6" width="2" height="2" fill="white"/>
        <rect x="10" y="7" width="2" height="2" fill="white"/>
        <rect x="7" y="6" width="2" height="2" fill="white"/>
        <rect x="12" y="8" width="2" height="2" fill="white"/>
        <rect x="14" y="8" width="2" height="2" fill="white"/>
        <rect x="11" y="7" width="2" height="2" fill="white"/>
        <rect x="16" y="9" width="2" height="2" fill="white"/>
        <rect x="16" y="6" width="2" height="2" fill="white"/>
        <rect x="13" y="5" width="2" height="2" fill="white"/>
        <rect x="18" y="7" width="2" height="2" fill="white"/>
        <rect x="11" y="5" width="2" height="2" fill="white"/>
        <rect x="8" y="4" width="2" height="2" fill="white"/>
        <rect x="13" y="6" width="2" height="2" fill="white"/>
        <rect x="15" y="6" width="2" height="2" fill="white"/>
        <rect x="12" y="5" width="2" height="2" fill="white"/>
        <rect x="17" y="7" width="2" height="2" fill="white"/>
        <rect x="17" y="4" width="2" height="2" fill="white"/>
        <rect x="14" y="3" width="2" height="2" fill="white"/>
        <rect x="19" y="5" width="2" height="2" fill="white"/>
        <rect x="6" y="9" width="2" height="2" fill="white"/>
        <rect x="3" y="8" width="2" height="2" fill="white"/>
        <rect x="8" y="10" width="2" height="2" fill="white"/>
        <rect x="10" y="10" width="2" height="2" fill="white"/>
        <rect x="7" y="9" width="2" height="2" fill="white"/>
        <rect x="12" y="11" width="2" height="2" fill="white"/>
        <rect x="12" y="8" width="2" height="2" fill="white"/>
        <rect x="9" y="7" width="2" height="2" fill="white"/>
        <rect x="14" y="9" width="2" height="2" fill="white"/>
        <rect x="8" y="2" width="2" height="2" fill="white"/>
        <rect x="11" y="4" width="2" height="2" fill="white"/>
        <rect x="12" y="3" width="2" height="2" fill="white"/>
        <rect x="15" y="5" width="2" height="2" fill="white"/>
        <rect x="14" y="1" width="2" height="2" fill="white"/>
        <rect x="17" y="3" width="2" height="2" fill="white"/>
        <rect x="10" y="3" width="2" height="2" fill="white"/>
        <rect x="13" y="5" width="2" height="2" fill="white"/>
        <rect x="14" y="4" width="2" height="2" fill="white"/>
        <rect x="17" y="6" width="2" height="2" fill="white"/>
        <rect x="16" y="2" width="2" height="2" fill="white"/>
        <rect x="19" y="4" width="2" height="2" fill="white"/>
        <rect x="9" y="5" width="2" height="2" fill="white"/>
        <rect x="12" y="7" width="2" height="2" fill="white"/>
        <rect x="13" y="6" width="2" height="2" fill="white"/>
        <rect x="16" y="8" width="2" height="2" fill="white"/>
        <rect x="15" y="4" width="2" height="2" fill="white"/>
        <rect x="18" y="6" width="2" height="2" fill="white"/>
        <rect x="11" y="6" width="2" height="2" fill="white"/>
        <rect x="14" y="8" width="2" height="2" fill="white"/>
        <rect x="15" y="7" width="2" height="2" fill="white"/>
        <rect x="18" y="9" width="2" height="2" fill="white"/>
        <rect x="17" y="5" width="2" height="2" fill="white"/>
        <rect x="20" y="7" width="2" height="2" fill="white"/>
        <rect x="12" y="4" width="2" height="2" fill="white"/>
        <rect x="15" y="6" width="2" height="2" fill="white"/>
        <rect x="16" y="5" width="2" height="2" fill="white"/>
        <rect x="19" y="7" width="2" height="2" fill="white"/>
        <rect x="18" y="3" width="2" height="2" fill="white"/>
        <rect x="21" y="5" width="2" height="2" fill="white"/>
        <rect x="12" y="2" width="2" height="2" fill="white"/>
        <rect x="15" y="4" width="2" height="2" fill="white"/>
        <rect x="16" y="3" width="2" height="2" fill="white"/>
        <rect x="19" y="5" width="2" height="2" fill="white"/>
        <rect x="18" y="1" width="2" height="2" fill="white"/>
        <rect x="21" y="3" width="2" height="2" fill="white"/>
        <rect x="11" y="4" width="2" height="2" fill="white"/>
        <rect x="14" y="6" width="2" height="2" fill="white"/>
        <rect x="15" y="5" width="2" height="2" fill="white"/>
        <rect x="18" y="7" width="2" height="2" fill="white"/>
        <rect x="17" y="3" width="2" height="2" fill="white"/>
        <rect x="20" y="5" width="2" height="2" fill="white"/>
        <rect x="13" y="5" width="2" height="2" fill="white"/>
        <rect x="16" y="7" width="2" height="2" fill="white"/>
        <rect x="17" y="6" width="2" height="2" fill="white"/>
        <rect x="20" y="8" width="2" height="2" fill="white"/>
        <rect x="19" y="4" width="2" height="2" fill="white"/>
        <rect x="22" y="6" width="2" height="2" fill="white"/>
        <rect x="14" y="3" width="2" height="2" fill="white"/>
        <rect x="17" y="5" width="2" height="2" fill="white"/>
        <rect x="18" y="4" width="2" height="2" fill="white"/>
        <rect x="21" y="6" width="2" height="2" fill="white"/>
        <rect x="20" y="2" width="2" height="2" fill="white"/>
        <rect x="23" y="4" width="2" height="2" fill="white"/>
        <rect x="9" y="7" width="2" height="2" fill="white"/>
        <rect x="12" y="9" width="2" height="2" fill="white"/>
        <rect x="13" y="8" width="2" height="2" fill="white"/>
        <rect x="16" y="10" width="2" height="2" fill="white"/>
        <rect x="15" y="6" width="2" height="2" fill="white"/>
        <rect x="18" y="8" width="2" height="2" fill="white"/>
      </svg>
</template>